apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-pv
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:dynamic-pv
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:dynamic-pv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:dynamic-pv
subjects:
- kind: ServiceAccount
  name: dynamic-pv
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:dynamic-pv-psp
subjects:
- kind: ServiceAccount
  name: dynamic-pv
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: caas:infra-psp
  apiGroup: rbac.authorization.k8s.io
