---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-local-pv-provisoner-svc
  namespace: kube-system
  labels:
    app: dynamic-local-pv-mutator
spec:
  ports:
  - name: webhook
    port: 443
  selector:
    app: dynamic-local-pv-mutator